THRESHOLD=22

#CHECK_INTERVAL=30

BUNDLE_PERCENT=20

LOG_DIRS="$HOME/log-cleanup/logs/app1~$HOME/log-cleanup/logs/app2"

BACKUP_ENABLED=true

BACKUP_DIR="$HOME/log-cleanup/backup"

FILE_PATTERN="*.txt"

LOCK_FILE="/tmp/log-cleanup.lock"

LOG_FILE="$HOME/log-cleanup/cleanup.log"

MOUNT_POINT="/"



